### PR TITLE
Corrected some minor confusing instructions in README

### PR DESCRIPTION
**Pull request by PiyumalK**

### CODE REVIEW

**Comment by AdityaGupta150** [comment]
Sorry bhai but such PR doesn't do any good.

You already have 30 repos I see.

Either contribute some code, or other than the readme only.

**Comment by AdityaGupta150** [comment]
The labels will surely be removed after you some quality contribution even if small.

**Comment by PiyumalK** [comment]
Ok I'm sorry. I'll contribute some code soon

**Comment by AdityaGupta150** [comment]
Closing it.

**Pull request closed without merging**
