### PR TITLE
Better to reserve vectors before adding to it

### PR DESCRIPTION
**Pull request by abraham-john-paul**

### CODE REVIEW

**Review by AdityaGupta150 — APPROVED** [review]

**Comment by AdityaGupta150** [comment]
Thanks @abraham-john-paul for the PR  😄🎉 

I have removed the reserve statements for now.
Since one plan for this is _to have ability to have more than 4 players possible_ too (since board size will change then), so the `15` all around may well be replaced by a Variable, but for simplicity is left so currently.

Also, `vector::reserve` is not much required for small lengths, and is required mainly for bigger arrays, since it has to allocate dynamically, and in case of bigger arrays, may have to copy the complete array to a new location if sufficient memory isn't available at a place, reserve prevents this by ensuring a block of memory is available at a position, smaller memory don't have this need, since at original position itself, it can allocate more.

**Comment by abraham-john-paul** [comment]
if you dont reserve the vector, wont the capacity grow while pushing like 2,4,8,16 like this, resulting in a lot of unnecessary copies

**Comment by AdityaGupta150** [comment]
I meant to say this, 
> When the memory allocated for the vector falls short of storing new elements, a new memory block is allocated to vector and all elements are copied from the old location to the new location. This reallocation of elements helps vectors to grow when required. However, it is a costly operation.

In case of smaller vectors, it's not much problematic (even if 16 blocks worth memory allocates for our 15), and that extra reserve isn't always _needed_, considering small vector optimisation, and compiler optimisation too.

Though, yes we can go with the change then, i will add the reserve statements ⚡

**Comment by abraham-john-paul** [comment]
Okay, thanks for explaining 🙂

**Pull request merged**
