### PR TITLE
React-based web app added

### PR DESCRIPTION
**Pull request by Athi223**
1.Basic logic done
2. Safe places for gotis added (start position of every color & 4 star places)

### CODE REVIEW

**Comment by AdityaGupta150** [comment]
@Athi223 It would really be great, if comments are added, rest other things now, will be sorted out in time 😄 .

Have a look at this, (the issues are just add space here and there in css, it will be fixed automatically)

pr

The game works quite well 🎉🎉 , though comments will be helpful, i  couldn't actually completely complete the game anytime, but that can be fixed with a better understanding, and since it's version 1, and @Athi223 really you gave good amount of time to create it 👍🏽 .

**Review by AdityaGupta150 — APPROVED** [review]

**Comment by AdityaGupta150** [comment]
Thanks for adding those valuable comments, they will surely make it much better in understanding it 🎉 
👍🏽

**Comment by AdityaGupta150** [comment]
@Athi223 You have contributed a major portion to it, want to be labeled as a `Collaborator` 😄 ?

Though even if you will be a collaborator, please don't modify the repo settings(can't now, but anyways), though you will also have more privilages than a contributor. 🚀

**Comment by Athi223** [comment]
> The complexity count shows mainly that some functions have multiple ways they will execute, so it's needed to have a better understanding to work on it, or if someone next wants to add to it.
>

Yeah even I'm exploring JS & React both so I'll myself have to figure out the best practices for implementing various things. I'll try to improve the logic as and when time permits.


> @Athi223 You have contributed a major portion to it, want to be labeled as a `Collaborator` smile ?
> 
Yes sure! Hopefully we'll also work on the `Online multiplayer` logic someday. That'll probably be the most interesting part i guess.


> Though even if you will be a collaborator, please don't modify the repo settings(can't now, but anyways), though you will also have more privilages than a contributor. rocket
> 
Yes dont worry about that haha. Its your repo so i can totally understand that you prefer managing the things by yourself (Since i myself like working on stuff on my own).

> This was my first interacting this much on GitHub, it has been great, and Thank You from my side 1234 👍🏽
Same here mate! Apart from those simple PRs for _hacktoberfest_, which hardly had any kind of _interaction_ with the maintainers; so this was my first meaningful contribution as such. Thanks to you too!

**Pull request merged**
